### ISSUE TITLE
Indigo / Ubuntu 14.04 version?

### ISSUE THREAD

**Issue by whitmanjack24** [osrf/car_demo#15]
This project is awesome, thank you for creating it!!

Do you guys have any plans for making an Indigo / Ubuntu 14.04 version of it?

**Comment by tfoote** [comment]
Glad you like it!

There are no plans to backport it to indigo / trusty. It's certainly doable and many of the components are already compatible and or available in indigo. This is a demo we put together and thought that we'd share not a maintained released package. All the components in this package should be released independently at some point too.
