### ISSUE TITLE
Offset base_link and chassis

### ISSUE THREAD

**Issue by jkooij** [osrf/car_demo#16]
Could you elaborate why there base_link_connection adds an offset of 1.45 meters between the chassis and base_link? The base_link is now located next to the vehicle, while I expected it to be near its center or rear axis. Not sure if this is a bug or a feature ...

Very nice demo by the way!

**Comment by tfoote** [comment]
Thanks we're glad you like the demo.

That's a bug. It was supposed to be under the rear axle but we tweaked the car position and didn't get around to resolving the orientation since the demo still worked. I opened a PR to put it back where people would expect it.
