### ISSUE TITLE
a few startup issues and questions

### ISSUE THREAD

**Issue by huckl3b3rry87** [osrf/car_demo#19]
First of all very cool package, it was the first time that I used docker and I like how easy it was to get running. Previously I had built ros and Gazebo from source, but I followed the Docker file and installed them on my machine that way to get things running.

**1. Information on project goal**
This is a great example of using a bunch of packages in a high level way to get things done quickly. It seems like the intention was to demonstrate this and allow the user to play with the simulation. Correct me if I am wrong but it seems like this was not intended to be a sort of "test bed" for researchers. If that is the case then perhaps this issue is a bit out of line. 

Personally, I would like to quickly test my algorithm (MPC path planning and moving obstacle avoidance) without spending too much time developing the simulation environment. Perhaps this repo or another repo could provide researchers the capability to test their algorithms? Perhaps a standard and well defined set of messages and default backends for particular tasks. For instance if a researcher wanted to predict the future movement of obstacles based off of LiDAR data, then they could leave the default backend for path planning. I realize that this is a lot of work, but it would be extremely useful, especially from a benchmarking perspective. 

**2. Additional Packages**
If you install this from debian you also need:
```
sudo apt-get install -y ros-kinetic-robot-state-publisher
sudo apt-get install -y ros-kinetic-rviz
```
I am not sure how rviz worked using Docker, but it was not installed during my fresh build.

**3. The Joystick**
The joystick worked on Docker, but it does not work on my new build. In both cases I get this error printing repeatedly:
```
[ERROR] [1506656598.132534, 1698.131000]: bad callback: <bound method Translator.callback of <__main__.Translator instance at 0x7ff6cb447ea8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/febbo/catkin_ws/src/car_demo/car_demo/nodes/joystick_translator", line 43, in callback
    if message.axes[THROTTLE_AXIS] >= 0:
IndexError: tuple index out of range
```
On my new build the joystick is printing to the screen:
```
cat /dev/input/js0
0;t9�0;t�0;tN>��<tx>tHx>ty>@t
```
Then taking a look at the joy topic:
```
rostopic echo joy
header: 
  seq: 129
  stamp: 
    secs: 1386
    nsecs: 499000000
  frame_id: ''
axes: [-0.0, -0.0, -0.47784435749053955]
buttons: []
````
It does not change when I hit buttons and move the sticks. ( I bought the Logitech 710 for this).

Also, I am able to control the vehicle directly from the keyboard.

**4. Documentation**
I guess that this one depends on what the intentions for this project are. But if you are amenable to building a virtual testbed for researchers, I can help with this. 

All in all, thanks again and I apologize if I am out of line with all of this.

p.s. is someone working at MCity?! I am at Michigan!

**Comment by tfoote** [comment]
Thanks for the feedback. We've put this together quickly for a demo and are not planning to actively maintain/develop it beyond showing off the demo. It definitely is a great start toward having a standard platform for testing algorithms. We'd love to have that happen but don't have resources to target that in the mean time.

If you would like to work toward making this into a easy test bed that would be great. I'd suggest forking it and working a little bit independently to let yourself run faster. But we'd definitely be open to merging back some of the lowerlevel fixes you had above. And if turning it into a test bed doesn't disrupt the demo that would be great too.

**Comment by huckl3b3rry87** [comment]
@tfoote thank you very much for your response, it seems (at least for now) that I will be developing using this repo as a sandbox and I will keep those requirements in mind as I develop things. 

Thanks!

**Comment by tfoote** [comment]
In reviewing #18 I got a chance to look a little closer at your issues. I'm going to close this as there's nothing to track. But I had a few debugging/helping tips for some of your comments.

> 2. Additional Packages
> If you install this from debian you also need:
> 
> sudo apt-get install -y ros-kinetic-robot-state-publisher
> sudo apt-get install -y ros-kinetic-rviz
> I am not sure how rviz worked using Docker, but it was not installed during my fresh build.

For anyone following this the Dockerfile starts from desktop so you'll want to install ros-kinetic-desktop which has rviz bundled inside.

> Then taking a look at the joy topic:
> 
> rostopic echo joy
> header: 
>   seq: 129
>   stamp: 
>     secs: 1386
>     nsecs: 499000000
>   frame_id: ''
> axes: [-0.0, -0.0, -0.47784435749053955]
> buttons: []
> It does not change when I hit buttons and move the sticks. ( I bought the Logitech 710 for this).

This is very limited. The Logitech has way more axes and buttons than this. It might be that you have some other joystick device on your system as js0?

**Comment by huckl3b3rry87** [comment]
@tfoote sorry for the delay.

Yes, I was actually pushing to ``js1``. I had switched ports where the USB was plugged in (and removed the ``js1`` option from the launch file). I initially did this to get ride of the error:
```
[ERROR] [1508785894.013048, 2124.653000]: bad callback: <bound method Translator.callback of <__main__.Translator instance at 0x7fd228c31ea8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/febbo/catkin_ws/src/car_demo/car_demo/nodes/joystick_translator", line 43, in callback
    if message.axes[THROTTLE_AXIS] >= 0:
IndexError: tuple index out of range
```
Which appears (for me) when two nodes are connected to the joystick.

So, now everything is working great!
