### ISSUE TITLE
How to modify run_bash script to run another launch script ? 

### ISSUE THREAD

**Issue by GuillaumeHauss** [osrf/car_demo#23]
Hi all, 

Forgive me if it's a newbie question, but I'm not very used to Docker app. 
I can execute the run_demo.basch script and everything is fine. The thing is that I don't need all these sensors on my model. 
So I copied-paste the prius.sdf file, get rid of what I needn't, changed the model parameter in the demo.launch file.
But the full demo car is used everytime I execute run_demo.bash, and my changes are taken in account. 

I've looked into the script and it's not very clear what file is used to launch the whole system. 
Can anyone tell me how to launch my custome launch file?

thank you very much in advance
Guillaume

**Comment by GuillaumeHauss** [comment]
Nvm I've found a way : just need to rebuild the docker image and rerun it. It's not a good solution I think, but so far, it works. If anyone has a better idea, I'll be happy to test it !

**Comment by menson168** [comment]
@GuillaumeHauss How do you rebuild a docker image?

**Comment by sloretz** [comment]
@menson168 Deleting the image manually works fine. Another option is edit the build script to edit the build script to add `--no-cache`

 `sudo docker build --no-cache -t osrf/car_demo $DIR`

More info at https://docs.docker.com/engine/reference/commandline/build/

**Comment by ruffsl** [comment]
You shouldn't have to rebuild the docker image from scratch if all you want to do is run a different roslaunch file. You can provided a different runtime command to override what is defaulted in the last layer of the docker file:
https://github.com/osrf/car_demo/blob/5c91f7e27a1c4f40fb946c6acc1474d2bc5b7ad0/Dockerfile#L37

by just passing the argument to `docker run` command. However, is sound's like you want to modify or add some files to docker image as well. I'd suggest, if your just prototyping, to make you changs, e.g. using`COPY` or `ADD` in the later sections of the dockerfile to preserve more of the build cache to save time.

Better yet, could just mount a directory from the host into the container with the files you are actively editing using the `--volume` argument with `docker run` command.
