### ISSUE TITLE
Change the interface of car to take torque as input

### ISSUE THREAD

**Issue by txzhao** [osrf/car_demo#28]
Hi,

First of all, thanks for open-sourcing this amazing work! I actually forked this repo and managed to connect a PID controller (outputs: throttle, brake) to it to control the car. The results are satisfactory. However when I want to change the output interface of the PID controller to torques of the 4 wheels, we find it hard to match or transform them with the inputs of the car_demo, namely throttle and brake. 

So my question is, could you give me some hints on how to change the interface of the car to take the torque of individual wheel as input? I tried to locate the relevant parts of code but ended up drowning in the piles of code. Thanks in advance.

BR/Tianxiao

**Comment by tfoote** [comment]
The HybridPriusDrive plugin controls all those aspects internally. You will have to replace it with standard joint plugins for the wheels. If you want more information I'd recommend the basic gazebo tutorials for joint control.

**Comment by txzhao** [comment]
Thanks. I'll take a look!
