### ISSUE TITLE
Missing "prius_msgs/Control.h"

### ISSUE THREAD

**Issue by pedrosantospt** [osrf/car_demo#33]
```
In file included from /tmp/workspace/src/car_demo/plugins/PriusHybridPlugin.cc:27:0:
/tmp/workspace/src/car_demo/plugins/PriusHybridPlugin.hh:29:32: fatal error: prius_msgs/Control.h: No such file or directory
compilation terminated.
make[2]: *** [car_demo/CMakeFiles/PriusHybridPlugin.dir/plugins/PriusHybridPlugin.cc.o] Error 1
```

Regards,
Pedro Santos

**Comment by tfoote** [comment]
Please provide more information about how to reproduce your error.

**Comment by mikaelarguedas** [comment]
My guess is that this [plugin](https://github.com/osrf/car_demo/blob/5c91f7e27a1c4f40fb946c6acc1474d2bc5b7ad0/car_demo/CMakeLists.txt#L27)  is missing a dependency on `prius_msgs`

**Comment by pedrosantospt** [comment]
I already found why this is happening.
Sometimes, for some reason, docker don't stop the container (after the CTRL+C) and if you try to run the ./build_demo.bash with some modification in code will give you that error.

**Reproduce the error**: Run ./run_demo.bash, modify the launch code and run ./build_demo.bash, while demo is running.
**Solution**: Stop the ./run_demo.bash or (if ./run_demo.bash stopped) restart docker service (sudo /etc/init.d/docker restart).

**Comment by tfoote** [comment]
Thanks for the follow up. I'm going to close this issue as it seems that the fix is to just make sure the containers is stopped.
