### ISSUE TITLE
gazebo_ros_block_laser.cpp no member GetSimTime

### ISSUE THREAD

**Issue by RodBelaFarin** [osrf/car_demo#35]
Using 16.04 and ROS Kinetic with Gazebo 9

Building car_demo with catkin_make generates an error in the plugin gazebo_ros_block_laser.cpp as follows:

```
/home/ros/catkin_ws/src/car_demo/car_demo/plugins/gazebo_ros_block_laser.cpp:85:37: error: ‘class gazebo::physics::World’ has no member named ‘GetSimTime’
   last_update_time_ = this->world_->GetSimTime();
                                     ^
/home/ros/catkin_ws/src/car_demo/car_demo/plugins/gazebo_ros_block_laser.cpp: In member function ‘void gazebo::GazeboRosBlockLaser::OnStats(const boost::shared_ptr<const gazebo::msgs::WorldStatistics>&)’:
/home/ros/catkin_ws/src/car_demo/car_demo/plugins/gazebo_ros_block_laser.cpp:408:3: error: ‘math’ has not been declared
   math::Pose pose;
   ^
/home/ros/catkin_ws/src/car_demo/car_demo/plugins/gazebo_ros_block_laser.cpp:409:3: error: ‘pose’ was not declared in this scope
   pose.pos.x = 0.5*sin(0.01*this->sim_time_.Double());
   ^

```

GetSimTime is not a class member of gazebo::physics::World -> Probably because I use Gazebo 9 instead of Gazebo 8?!

**Comment by RodBelaFarin** [comment]
Yes, you are right...

```
/home/ros/catkin_ws/src/car_demo/car_demo/plugins/gazebo_ros_block_laser.cpp:409:8: error: ‘ignition::math::v4::Pose3d {aka class ignition::math::v4::Pose3<double>}’ has no member named ‘pos’
   pose.pos.x = 0.5*sin(0.01*this->sim_time_.Double());
```

Is there any chance this package will be ported to Gazebo9 soon? There is now the very awesome [citysim](https://bitbucket.org/osrf/citysim) world in Gazebo9 and it would be great to include the ROS car_demo from here.

**Comment by tfoote** [comment]
The demo is working as implemented. We're not actively porting this forward. However if you or someone else would like to contribute porting this forward to gazebo9 that contribution would be happily accepted.

**Comment by YoshiRi** [comment]
Hi. I had the same problem and seems to have solved this issue.
I updated two parts as RodBelaFarin says.

```c++
//last_update_time_ = this->world_->GetSimTime();
last_update_time_ = this->world_->SimTime();
```

```c++
void GazeboRosBlockLaser::OnStats( const boost::shared_ptr<msgs::WorldStatistics const> &_msg)
{
  this->sim_time_  = msgs::Convert( _msg->sim_time() );

  //math::Pose pose;
  //pose.pos.x = 0.5*sin(0.01*this->sim_time_.Double());
  gzdbg << "plugin simTime [" << this->sim_time_.Double() << "] update pose [" << 0.5*sin(0.01*this->sim_time_.Double()) << "]\n";
}
```

This solution seems to be not smart but it actually works.

**Comment by 21Ansh** [comment]
I have fixed the issues related to Gazebo 9. Check out the following link

https://github.com/21Ansh/velo2cam_gazebo

**Comment by tfoote** [comment]
With the closure of #4 this code is no longer in this repository. I suspect that this is already resolved upstream. If not please open an issue at: https://github.com/ros-simulation/gazebo_ros_pkgs
