### ISSUE TITLE
How to judge whether the car is or not  Out of the lane？

### ISSUE THREAD

**Issue by HubFire** [osrf/car_demo#37]
Hello ，I am doing   self-driving simulation based on  gazebo and DRL. Thanks for developing  such  a  prius simulation car.But how can I  judge whether the car is t out of the lane  in gazebo .

**Comment by tfoote** [comment]
If you want ground truth you'll likely want to write a plugin that introspects the models in the world and can score it.

**Comment by tfoote** [comment]
Closing since this isn't really an actionable issue.
