### ISSUE TITLE
Rosbags usage

### ISSUE THREAD

**Issue by Brunovieira8** [osrf/car_demo#45]
Dear all,

I'm using your prius model in simulation model i'm developing, and would like to record some rosbags within a simulation on it. I use a simple application(attachment) with keyboard inputs for the car to get around the map I have. 

My goal is to have this car to do the same path everytime i run my simulation, I tried using rosbags for this purpose, but i'm having problems with them, they don't replicate the car's path from the simulation it was recorded under, for example, it starts to turn earlier than it should... Any idea on what can this be happening?

Or do you have any suggestion on how to do this without using rosbags? I dont know if you have some autonomous controller already developed for a exact environment...

Hope you can help me on this.
thanks,
Bruno Vieira
[code.txt](https://github.com/osrf/car_demo/files/2691642/code.txt)

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
