### ISSUE TITLE
car_demo with autonomous control

### ISSUE THREAD

**Issue by Brunovieira8** [osrf/car_demo#52]
Dear all,

Is there any project done that included the Prius model developed under this repository that enables autonomous driving of it on a gazebo simulation? Like a line following algorithm or even a path-planner...
Need to be able to implement a simple autonomous controller for your model to be able to replicate simulation runs, since manually controlling it is not scientifically-reliant...

Any idea of something that might be useful for this purpose?

Best regards,
Bruno Vieira

**Comment by tfoote** [comment]
Yes there are autonomous driving implementations that can be hooked up to this simulation. However that's out of scope of this repo/demo.

**Comment by Brunovieira8** [comment]
I know it is out-of-scope of this repo, however my question was related to implementation specifically done using this model... Would like to get some references if any is known...
