### ISSUE TITLE
Some issues when i attempt to control two prius car in gazebo

### ISSUE THREAD

**Issue by wsustcid** [osrf/car_demo#53]
**Hello everyone!
    I'd like to control  two prius cars in gazebo to preform some leader-follower experiments. So I write a two_car.launch file spawning the prius.urdf two times with different group namespace.** 
![two_car_launch](https://user-images.githubusercontent.com/32996215/53301695-05c94280-3891-11e9-8bef-9f84009dbd53.png)

The two_car.launch file can be found in the following link:
[https://github.com/wsustcid/car_demo/blob/nvidia-docker/car_demo/launch/two_car.launch](url)
      

**Finally, two prius car  showed in gazebo successfully but the ros topic is weird. The camera related topics have desired group namespace (Messages can also be echoed from these topics), but the control topic "/prius" showed without the group namespace. And the original topics also exist while no messages published from these topics. I think the problem is due to the custom PriusHybridPlugin, but i don't know why...**

`
ubuntu16@ubuntu16:~/catkin_ws$ rostopic list
/clicked_point
/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/gazebo_gui/parameter_descriptions
/gazebo_gui/parameter_updates
/initialpose
/move_base_simple/goal
/prius
/prius/back_camera/image_raw
/prius/back_camera_info
/prius/back_sonar/left_far_range
/prius/back_sonar/left_middle_range
/prius/back_sonar/right_far_range
/prius/back_sonar/right_middle_range
/prius/center_laser/scan
/prius/front_camera/image_raw
/prius/front_camera_info
/prius/front_left_laser/scan
/prius/front_right_laser/scan
/prius/front_sonar/left_far_range
/prius/front_sonar/left_middle_range
/prius/front_sonar/right_far_range
/prius/front_sonar/right_middle_range
/prius/left_camera/image_raw
/prius/left_camera_info
/prius/right_camera/image_raw
/prius/right_camera_info
/prius1/amcl_pose
/prius1/base_pose_ground_truth
/prius1/initialpose
/prius1/joint_states
/prius1/particlecloud
/prius1/prius/back_camera/image_raw
/prius1/prius/back_camera/parameter_descriptions
/prius1/prius/back_camera/parameter_updates
/prius1/prius/front_camera/image_raw
/prius1/prius/front_camera/parameter_descriptions
/prius1/prius/front_camera/parameter_updates
/prius1/prius/left_camera/image_raw
/prius1/prius/left_camera/parameter_descriptions
/prius1/prius/left_camera/parameter_updates
/prius1/prius/right_camera/image_raw
/prius1/prius/right_camera/parameter_descriptions
/prius1/prius/right_camera/parameter_updates
/prius2/amcl_pose
/prius2/base_pose_ground_truth
/prius2/initialpose
/prius2/joint_states
/prius2/particlecloud
/prius2/prius/back_camera/image_raw
/prius2/prius/back_camera/parameter_descriptions
/prius2/prius/back_camera/parameter_updates
/prius2/prius/front_camera/image_raw
/prius2/prius/front_camera/parameter_descriptions
/prius2/prius/front_camera/parameter_updates
/prius2/prius/left_camera/image_raw
/prius2/prius/left_camera/parameter_descriptions
/prius2/prius/left_camera/parameter_updates
/prius2/prius/right_camera/image_raw
/prius2/prius/right_camera/parameter_descriptions
/prius2/prius/right_camera/parameter_updates
/rosout
/rosout_agg
/tf
/tf_static |
`

Note that the newest version of the car_demo code can not run successfully on my computer after some efforts, so i still use the old version 5c91f7e which commits on  Oct 31, 2017.

I would be very grateful if you have any suggestions！

**Comment by tfoote** [comment]
You will need to look under the hood to see if the implementation is using a leading slash or not. Likely it is and thus it will not respect a pushdown namespace remapping.

**Comment by MustafaIsmaill** [comment]
@wsustcid Hello Shuai, have you been able to find a solution to this? I am facing the same issue when I launch multiple vehicles of the same type.
Your input would be really helpful.

**Comment by wsustcid** [comment]
@MustafaIsmaill Hi MustafaIsmaill, I have no solution to solve this problem now. I think the multiple prius cars cannot be spawned successfully by using the default 'spawn_model' (especially for spawning the topics). In another simulation project, multiple self-driving cars can be spawned with a custom spawn node. Unfortunately, this node is undisclosed and we cannot know how to achieve that.

**Comment by WangJintao1998** [comment]
Topics became normal after I deleted the leading slash in .urdf file.
