### ISSUE TITLE
ROS Melodic compatibility

### ISSUE THREAD

**Issue by visinescu13** [osrf/car_demo#57]
Hello,

I try to run run_demo.bash in my **Ubuntu 18.04** using **ROS Melodic** but I have a lot of errors that can be seen in the [log](https://pastebin.com/raw/F1RDms9s).
I see /rosdistro: kinetic when the roslaunch server is started. And also I see "kinetic" word in many places in log.

Please let me know if I can use the Melodic distribution or I should switch to Kinetic.

**Comment by visinescu13** [comment]
Update: I modified **Dockerfile** and replaced **kinetic** with **melodic** but I still see errors. Please refer to this [log](https://pastebin.com/raw/WCQS3D9H).

**Comment by tfoote** [comment]
There is work in #43 for supporting melodic, but it's untested at the moment.
