### ISSUE TITLE
There is no gazebo and rviz after starting run_demo.bash.

### ISSUE THREAD

**Issue by shmily-skx** [osrf/car_demo#58]
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
The directory '/home/shmily/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/shmily/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/osrf/rocker.git
  Cloning https://github.com/osrf/rocker.git to /tmp/pip-0wyvyo0m-build
Requirement already up-to-date: empy in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from rocker===0.1.4)
Requirement already up-to-date: pexpect in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from rocker===0.1.4)
Requirement already up-to-date: docker-py in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from rocker===0.1.4)
Requirement already up-to-date: ptyprocess>=0.5 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from pexpect->rocker===0.1.4)
Requirement already up-to-date: requests!=2.11.0,>=2.5.2 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from docker-py->rocker===0.1.4)
Requirement already up-to-date: six>=1.4.0 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from docker-py->rocker===0.1.4)
Requirement already up-to-date: docker-pycreds>=0.2.1 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from docker-py->rocker===0.1.4)
Requirement already up-to-date: websocket-client>=0.32.0 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from docker-py->rocker===0.1.4)
Requirement already up-to-date: urllib3<1.25,>=1.21.1 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py->rocker===0.1.4)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py->rocker===0.1.4)
Requirement already up-to-date: certifi>=2017.4.17 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py->rocker===0.1.4)
Requirement already up-to-date: idna<2.9,>=2.5 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py->rocker===0.1.4)
Installing collected packages: rocker
  Found existing installation: rocker 0.1.4
    Uninstalling rocker-0.1.4:
      Successfully uninstalled rocker-0.1.4
  Running setup.py install for rocker ... done
Successfully installed rocker-0.1.4
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Plugins found: ['dev_helpers', 'home', 'nvidia', 'pulse', 'user', 'x11']
Active extensions ['nvidia', 'user']

Then stop at this interface

**Comment by tfoote** [comment]
There does not appear to be enough information to classify this as a bug report. Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

When you do please provide enough information to reproduce your issue. Describe your full environment and everything you did to set it up, all the commands that you ran as well as the full outputs. If it gets verbose you can put them into a gist.
