### ISSUE TITLE
Build_demo fail

### ISSUE THREAD

**Issue by dongyy1148** [osrf/car_demo#63]
Hi,
I just start to use your packages and just get two questions.
1. When I run ./build_demo.bash, i get the error like:
![image](https://user-images.githubusercontent.com/43221681/59969047-c515c900-9512-11e9-8ccd-e0815dd76083.png)
Why does it need 1 argument?
2. For now, I use ROS kinetic and gazebo 7.0. Will it be a problem to use gazebo 7.0 not 9.0 to run your Mcity demo?
Thanks!

**Comment by dongyy1148** [comment]
Anyone can help? Thanks!

**Comment by tfoote** [comment]
Please edit you post to not use a screenshot but copy and past the content so it's highlightable, searchable and copyable as text. In addition provide enought information to fully reproduce your proble, not just a partial output from your console. 

Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
