### ISSUE TITLE
run_demo.bash issue

### ISSUE THREAD

**Issue by yeonjisong** [osrf/car_demo#71]
When i run ./run_demo.bash, I get the following error:

`
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
`

**Comment by sloretz** [comment]
Hi @yeonjisong, this looks like an issue with the nvidia-docker installation on that machine. There's a related open issue upstream:

https://github.com/NVIDIA/nvidia-docker/issues/1243

I'll close this for now, but feel free to keep commenting if you find a solution or discover there's something this repo could do better.
