### ISSUE TITLE
Give throttle from python script

### ISSUE THREAD

**Issue by kadirtunc** [osrf/car_demo#72]
Hello I am working on a car simulation with prius hybrid. How can I give a throttle and steer from python script? I tried with Control.msg to "prius" publisher. I tried to set joint states but I cannot manage it. Could you help me about this?

**Comment by sloretz** [comment]
[`joystic_translator` script](https://github.com/osrf/car_demo/blob/master/car_demo/nodes/joystick_translator) is an example of giving throttle and steering from a python script. It publishes a message of [type `prius_msgs.msg.Control`](https://github.com/osrf/car_demo/blob/master/prius_msgs/msg/Control.msg) to [the `prius` topic](https://github.com/osrf/car_demo/blob/38a4686dd573739dcd237187030efba3ce4913b0/car_demo/nodes/joystick_translator#L30).

> I tried with Control.msg to "prius" publisher

It sounds like you've tried the above already, but there may be a bug in the script you're working on. For more detailed help, please open a question on https://answers.ros.org with a minimal reproducible example.
